[package]
name = "picker"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.0"
dotenvy = "0.15.7"
env_logger = "0.10.1"
sea-orm = { version = "0.12.7", features = [
  "sqlx-postgres",
  "runtime-actix-native-tls",
  "macros",
], default-features = false}
serde = "1.0.193"
